name: Surf
version: 1.0
description: Surf for Spigot
load: POSTWORLD
author: batthomas
main: ch.batthomas.surf.Surf
database: true
commands:
    nextround:
    stats:
    setup:
    setspawn:
    level:
        aliases: lvl